// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy5NNMskJce00CAl7D28Ee5jcnyGznKFc',
    appId: '1:109182022658:web:b581c93a419c2118efe31b',
    messagingSenderId: '109182022658',
    projectId: 'qlynhahang-415dc',
    authDomain: 'qlynhahang-415dc.firebaseapp.com',
    storageBucket: 'qlynhahang-415dc.firebasestorage.app',
    measurementId: 'G-DN8RBJMZNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXh647-jkyx8-hKXMWY7ukYGJNVtihFpI',
    appId: '1:109182022658:android:7f80712a11f126bbefe31b',
    messagingSenderId: '109182022658',
    projectId: 'qlynhahang-415dc',
    storageBucket: 'qlynhahang-415dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg10b-nx-uv7M9fX7nYB1RRaY11etUnxY',
    appId: '1:109182022658:ios:d025eb80104cc6eaefe31b',
    messagingSenderId: '109182022658',
    projectId: 'qlynhahang-415dc',
    storageBucket: 'qlynhahang-415dc.firebasestorage.app',
    iosBundleId: 'com.example.quanlyNhahang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg10b-nx-uv7M9fX7nYB1RRaY11etUnxY',
    appId: '1:109182022658:ios:d025eb80104cc6eaefe31b',
    messagingSenderId: '109182022658',
    projectId: 'qlynhahang-415dc',
    storageBucket: 'qlynhahang-415dc.firebasestorage.app',
    iosBundleId: 'com.example.quanlyNhahang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy5NNMskJce00CAl7D28Ee5jcnyGznKFc',
    appId: '1:109182022658:web:ab37b5942083f30defe31b',
    messagingSenderId: '109182022658',
    projectId: 'qlynhahang-415dc',
    authDomain: 'qlynhahang-415dc.firebaseapp.com',
    storageBucket: 'qlynhahang-415dc.firebasestorage.app',
    measurementId: 'G-71MKNPDCWD',
  );
}
